### ISSUE TITLE
User authentication

### ISSUE THREAD

**Issue by Camelia03** [Camelia03/go_global_project#2]
- [ ] Camelia03/new_project#4 
- [ ] Camelia03/new_project#5 
- [ ] Camelia03/new_project#6
